### ISSUE TITLE
Work page "Add to Collection" does not work

### ISSUE THREAD

**Issue by DiemBTran** [notch8/atla_digital_library#198] opened 2022-11-16 00:18 UTC
When I am logged in and go to an item in the DL and click “Add to Collection” it is not possible to pull up any collections by name to add the work to. 

In this example I am trying to add this work to “Swarthmore College Friends Historical Library” collection, so I start to type Swarthmore but get no results. The dropdown shows a couple random collections to choose from, not relevant collection.

![Image](https://user-images.githubusercontent.com/29311858/202052360-0fd9ee80-7de6-46c3-a2dd-13896ac40105.png)

**THIS MAY BE RELATED TO #211(Collection search box when adding/editing a work)**

**Comment by DiemBTran** [comment] 2022-11-16 00:19
Related MRs:

[start the search in select2 boxes without typing](https://gitlab.com/notch8/dot/-/merge_requests/212)
dot
!212

**Comment by DiemBTran** [comment] 2022-11-16 00:20
Christy - Jan 2022

---

This is still an issue. See ticket #211 Collection search box when adding/editing a work
 which i think may be related

**Comment by DiemBTran** [comment] 2022-11-16 00:20
April Jan 2022

---

Link to work reported by client above: https://dl.atla.com/concern/works/4b29bj68z?locale=en

I was able to enter in the text `swarthmore` and was able to see this specific collection the client was referring to in the dropdown menu. But to be clear I cannot pick anything from the drop down with the minimum of 2 characters (`Please enter 2 or more characters`) creating a bad user experience. 



![Image](https://user-images.githubusercontent.com/29311858/202052621-23bbf838-09ec-4360-95cc-9558655d96c0.png)

**Comment by DiemBTran** [comment] 2022-11-16 00:20
April Feb 2022:

---

https://samvera.slack.com/archives/C0F9JQJDQ/p1548975332439500

**Comment by DiemBTran** [comment] 2022-11-16 00:21
April Feb 2022:

---

Partial: https://github.com/samvera/hyrax/blob/v2.6.0/app/views/hyrax/dashboard/collections/\_form_for_select_collection.html.erb

**Comment by DiemBTran** [comment] 2022-11-16 00:21
April Feb 2022

---

https://github.com/samvera/hyrax/blob/v2.6.0/app/assets/javascripts/hyrax/autocomplete/default.es6#L11 This is where 2 is specified in the js. It is currently a bug in Hyrax 3 still. I went to Nurax and signed in as an Admin and tried to add a work to a collection and the collection name only appears when I type the full name in the box.

**Comment by DiemBTran** [comment] 2022-11-16 00:21
April Feb 2022:

---
Found it: https://gitlab.com/notch8/dot/-/merge_requests/212

**Comment by summer-cook** [comment] 2023-04-12 21:15
duplicate of #185

**Closed as completed** 2023-05-05 19:38 UTC
Labels: Blocked, Maintenance Task, SPRINT Team Prep
